
dataloader:
  root: data/processed
  normalization: stats/opensim_sincos_vel_acc_tau_v1/pretrain_v1_train_clean.pt
  batch_size: 8
  num_workers: 4
  window_frames: 256

  train:
    split_set: pretrain_v1
    split: train
    source_datasets: ["AMASS"]
  
  val:
    split_set: babel_official
    split: val
    source_datasets: ["AMASS"]

model:
  num_dofs: 43
  num_features: 5
  hidden_channels: 256
  depth: 3
  kernel_size: 5
  lr: 0.001
  loss_channels: [2, 3, 4]

training:
  seed: 13
  epochs: 20
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  overfit_batches: 0
